spring:
  application:
    name: router
  main:
    allow-bean-definition-overriding: true
server:
  port: 8886
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8887/eureka/
zuul:
  routes:
    service:
      path: /service/**
      serviceId: service
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN




